name: danabowo_financial_tracker
description: "Danabowo - Financial Tracker: A mobile application for tracking income and expenses with budgeting features."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  uuid: ^4.5.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  share_plus: ^10.0.3
  csv: ^6.0.0
  pdf: ^3.11.1
  path: ^1.9.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/
